name: green_screen_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.2.0  
  image_picker: ^0.8.7+4  
  audioplayers: ^6.4.0
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true


  assets:
    - assets/buddha_1_11zon.jpg  # ✅ renamed version
    - assets/animations/symbol_animation.gif
    - assets/animations/earth_day_celebration.jpg
    - assets/images/avatar.jpg
